"""
Artifact Management - Store and retrieve job outputs.

Artifacts are files generated by job execution:
- Text files (markdown, plain text, JSON)
- Images
- Videos
- Other binary files
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Optional
import json
import shutil

from config.settings import get_settings


@dataclass
class ArtifactInfo:
    """Information about a stored artifact."""

    job_id: str
    filename: str
    type: str
    label: str
    path: Path
    size_bytes: int


class ArtifactManager:
    """
    Manages artifact storage and retrieval.

    Artifacts are stored in:
    outputs/jobs/<job_id>/artifacts/<filename>
    """

    def __init__(self, base_path: Optional[Path] = None):
        """
        Initialize the artifact manager.

        Args:
            base_path: Base path for artifact storage
        """
        if base_path is None:
            settings = get_settings()
            base_path = Path(settings.output.base_path)

        self.base_path = base_path.resolve()
        self.jobs_path = self.base_path / "jobs"

        # Ensure directories exist
        self.jobs_path.mkdir(parents=True, exist_ok=True)

    def get_job_dir(self, job_id: str) -> Path:
        """
        Get the directory for a job's artifacts.

        Args:
            job_id: The job identifier

        Returns:
            Path: Job artifact directory
        """
        job_dir = self.jobs_path / job_id / "artifacts"
        job_dir.mkdir(parents=True, exist_ok=True)
        return job_dir

    def save_text(
        self, job_id: str, filename: str, content: str, label: Optional[str] = None
    ) -> ArtifactInfo:
        """
        Save a text artifact.

        Args:
            job_id: The job identifier
            filename: Output filename
            content: Text content
            label: Human-readable label

        Returns:
            ArtifactInfo: Saved artifact information
        """
        job_dir = self.get_job_dir(job_id)
        path = job_dir / filename

        path.write_text(content, encoding="utf-8")

        return ArtifactInfo(
            job_id=job_id,
            filename=filename,
            type="text",
            label=label or filename,
            path=path,
            size_bytes=path.stat().st_size,
        )

    def save_json(
        self, job_id: str, filename: str, data: dict, label: Optional[str] = None
    ) -> ArtifactInfo:
        """
        Save a JSON artifact.

        Args:
            job_id: The job identifier
            filename: Output filename (should end in .json)
            data: JSON-serializable data
            label: Human-readable label

        Returns:
            ArtifactInfo: Saved artifact information
        """
        job_dir = self.get_job_dir(job_id)
        path = job_dir / filename

        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)

        return ArtifactInfo(
            job_id=job_id,
            filename=filename,
            type="json",
            label=label or filename,
            path=path,
            size_bytes=path.stat().st_size,
        )

    def save_binary(
        self,
        job_id: str,
        filename: str,
        data: bytes,
        artifact_type: str,
        label: Optional[str] = None,
    ) -> ArtifactInfo:
        """
        Save a binary artifact.

        Args:
            job_id: The job identifier
            filename: Output filename
            data: Binary content
            artifact_type: Type (image, video, etc.)
            label: Human-readable label

        Returns:
            ArtifactInfo: Saved artifact information
        """
        job_dir = self.get_job_dir(job_id)
        path = job_dir / filename

        path.write_bytes(data)

        return ArtifactInfo(
            job_id=job_id,
            filename=filename,
            type=artifact_type,
            label=label or filename,
            path=path,
            size_bytes=path.stat().st_size,
        )

    def get_artifact_path(self, job_id: str, filename: str) -> Optional[Path]:
        """
        Get the full path to an artifact.

        Args:
            job_id: The job identifier
            filename: Artifact filename

        Returns:
            Path or None if not found
        """
        path = self.jobs_path / job_id / "artifacts" / filename
        return path if path.exists() else None

    def list_artifacts(self, job_id: str) -> list[ArtifactInfo]:
        """
        List all artifacts for a job.

        Args:
            job_id: The job identifier

        Returns:
            list[ArtifactInfo]: Job artifacts
        """
        job_dir = self.jobs_path / job_id / "artifacts"

        if not job_dir.exists():
            return []

        artifacts = []
        for path in job_dir.iterdir():
            if path.is_file():
                # Determine type from extension
                ext = path.suffix.lower()
                if ext in (".json",):
                    artifact_type = "json"
                elif ext in (".png", ".jpg", ".jpeg", ".gif", ".webp"):
                    artifact_type = "image"
                elif ext in (".mp4", ".webm", ".mov"):
                    artifact_type = "video"
                else:
                    artifact_type = "text"

                artifacts.append(
                    ArtifactInfo(
                        job_id=job_id,
                        filename=path.name,
                        type=artifact_type,
                        label=path.stem,
                        path=path,
                        size_bytes=path.stat().st_size,
                    )
                )

        return artifacts

    def delete_job_artifacts(self, job_id: str) -> bool:
        """
        Delete all artifacts for a job.

        Args:
            job_id: The job identifier

        Returns:
            bool: True if deleted
        """
        job_dir = self.jobs_path / job_id

        if job_dir.exists():
            shutil.rmtree(job_dir)
            return True

        return False

    def get_relative_path(self, artifact: ArtifactInfo) -> str:
        """
        Get the API-relative path for an artifact.

        Args:
            artifact: The artifact info

        Returns:
            str: Relative path for API access
        """
        return f"jobs/{artifact.job_id}/artifacts/{artifact.filename}"
